version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - django_network

  backend:
    build: .
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_PORT=5432
      - DB_NAME=mydatabase
    depends_on:
      - db
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local